# Generated by Django 5.2 on 2025-05-06 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('student', 'Student'), ('faculty', 'Faculty')], max_length=10)),
                ('courses', models.CharField(choices=[('math', 'Mathematics'), ('cs', 'Computer Science'), ('history', 'History'), ('physics', 'Physics'), ('english', 'English')], max_length=20)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
    ]
