# Generated by Django 5.2 on 2025-07-02 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='attendance_percentage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='student',
            name='certificates',
            field=models.TextField(blank=True, help_text='Comma-separated certificate names'),
        ),
        migrations.AddField(
            model_name='student',
            name='courses',
            field=models.TextField(blank=True, help_text='Comma-separated course names'),
        ),
        migrations.AddField(
            model_name='student',
            name='fee_due',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='student',
            name='fee_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='student',
            name='grades',
            field=models.TextField(blank=True, help_text='Comma-separated course:grade pairs'),
        ),
        migrations.AlterField(
            model_name='student',
            name='enrollment_number',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
