# Generated by Django 5.2 on 2025-07-03 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_student_attendance_percentage_student_certificates_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='certificates',
            field=models.ImageField(upload_to='certificates/'),
        ),
    ]
